### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by brucou** [rachidsakara/vue-news-app-with-vuetify#1]
Hi Rachid,

first of all congratulations for such a nice demo app and the accompanying article. I could not find the licensing terms for it, and I was wondering what they were. Could you put some light on that?

Thank you

**Comment by rachidsakara** [comment]
The application is under MIT licence:
https://github.com/rachidsakara/vue-news-app-with-vuetify/tree/add-license-1

**Comment by rachidsakara** [comment]
The Software is under MIT licence:
https://github.com/rachidsakara/vue-news-app-with-vuetify/tree/add-license-1

**Comment by brucou** [comment]
Thanks! Closing this
